---
- name: Create a file on all the servers
  hosts: all
  tasks:
    - name: File Creation
      file:
        name: /tmp/file1
        state: touch
        owner: Ravi
        group: root
        mode: 750
...
