---
- name: Error Handling or Exception Handling
  hosts: all
  tasks:
    - block:
       - name: Intall git using apt module
         apt:
           name: git
           state: present
           update_cache: yes
      rescue:
        - name: Install git using yum module
          yum:
            name: git
            state: present
            update_cache: yes
      always:
        - name: Pring success msg
          debug:
            msg: "Git installtion successfull"
